### ISSUE TITLE
Benchmarking and improving HMC/NUTS

### ISSUE THREAD

**Issue by yebai** [TuringLang/TuringExamples#19]
I suggest that we use this issue as an umbrella page for tracking improvements of benchmarking performances (memory, running time). For every new commit, we could write a small julia script to automatically (see [GitHub.jl](https://github.com/JuliaWeb/GitHub.jl#rest-methods)) post a new comment to this issue containing updated runtime information. 

Related issues:
- [x] Improving the speed of single program run TuringLang/Turing.jl#294
- [x] Using function type instead of Function may improve efficiency TuringLang/Turing.jl#300
- [x] Beyond vectorisation? TuringLang/Turing.jl#283
- [x] Use vec/parallelisation/GPU to speed up link/invlink TuringLang/Turing.jl#314
- [x] `ForwardDiff.gradient` is slow TuringLang/Turing.jl#234

**Comment by storopoli** [comment]
Guys do you need help to transfer Travis stuff to GitHub Actions?
